#Design de la page de librairie de Standard. Utilsiation de MkDocs (Générateur de site statique sur Github). 
#Set-up existant, le fichier est un gestionnaire de configuration

site_name: Librairie des Standards
site_description: Portail officiel des procédures
site_url: https://shibukawa310.github.io/Test-Lorem-Ipsum/

theme:
  name: material #Design de la page statique et adaptation à l'utlisation sur mobile
  language: fr # Pour avoir les boutons "Précédent/Suivant" et la recherche en français
  palette:
    primary: indigo # Vous pouvez choisir 'blue', 'red', 'teal', etc.
    accent: indigo
  features:
    - navigation.sections
    - navigation.top # Bouton pour remonter en haut de page
    - search.suggest
    - search.highlight

markdown_extensions: #Librairie pour les menus déroulants où les textes dynamique (Message d'erreur)
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
