#Utilisation du service Github Action. Automatisation d'une action répétitive.

name: Deploy-Site
on:
  push:      
    branches:   #Déclencheur de l'action après chaque modif sur la branche principale
      - main
  workflow_dispatch:  # C'est le bouton manuel
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x     #Language Mk Doc en python
      - run: pip install mkdocs-material     #Libraire de Python
      - run: mkdocs gh-deploy --force     #Conversion .md en html
